spring:
  # --------------------------------------------------------------------------
  # 0. Nombre de la Aplicación
  # --------------------------------------------------------------------------
  application:
    name: admision-academica

  # --------------------------------------------------------------------------
  # 1. Configuración de Spring Data JPA (PostgreSQL)
  # --------------------------------------------------------------------------
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_ql: true
    show-sql: true

  # --------------------------------------------------------------------------
  # 2. Configuración de Spring Data MongoDB
  # --------------------------------------------------------------------------
  data:
    mongodb:
      uri: ${MONGO_URI}
      # username: usuario_mongo
      # password: contrasena_mongo
  # --------------------------------------------------------------------------
  # 3. Observabilidad - TRACING (Micrometer + Brave)
  # --------------------------------------------------------------------------
  tracing:
    sampling:
      probability: 1.0 # ⚠ En producción usar 0.1 o 0.2
# --------------------------------------------------------------------------
# 4. Configuración de Seguridad JWT
# --------------------------------------------------------------------------
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000
      # refresh-token:
      #   expiration: 604800000

# --------------------------------------------------------------------------
# 5. Configuración del Servidor
# --------------------------------------------------------------------------
server:
  port: 8080



# --------------------------------------------------------------------------
# 6. ACTUATOR + MÉTRICAS (Prometheus / Grafana)
# --------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,env"

  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

# --------------------------------------------------------------------------
# 7. LOGGING (CRUCIAL PARA GRAFANA + LOKI)
# --------------------------------------------------------------------------
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"